### ISSUE TITLE
Tracking issue for CoRPC specification stabilization

### ISSUE THREAD

**Issue by Rirush** [Rirush/CoRPC#1]
This issue will keep track of all things that must be completed before specification can move from **draft** status to **expetimental**.

* [ ] Finalize service description message:
    * [ ] Service name: string or UUID?
    * [ ] Version fields: uint16, uint8 or other type?
    * [ ] Is there a need for multiple authentication methods?
* [ ] Finalize authentication methods:
    * [ ] Does `Anonymous` authentication method need support for custom fields?
    * [ ] Does `Credentials` authentication method need separate types for registration and authentication?
    * [ ] Is there a need for any other key type other than Ed25519 for TLS authentication?
* [ ] Finalize procedure calls:
    * [ ] Should packet types be unified for both server and client (e.g. type `0x01` refer to both error and success) or should they stay as they are?
* [ ] Finalize event notifications:
    * [x] Are acknowledgement and retransmission packets needed? **No**
* [ ] Finalize streams:
    * [x] Do streams need acknowledgement and retransmissions packets? **No**
